"""Public catalog facade for tool metadata and registry access."""

from __future__ import annotations

from mindroom.tool_system.metadata import (
    ConfigField,
    SetupType,
    TOOL_METADATA,
    _TOOL_REGISTRY,
    ToolAuthoredOverrideValidator,
    ToolCategory,
    ToolConfigOverrideError,
    ToolInitOverrideError,
    ToolMetadata,
    ToolMetadataValidationError,
    ToolStatus,
    ToolValidationInfo,
    apply_authored_overrides,
    authored_tool_overrides_to_runtime,
    capture_tool_registry_snapshot,
    clear_plugin_tool_registrations,
    default_worker_routed_tools,
    deserialize_tool_validation_snapshot,
    ensure_tool_registry_loaded,
    export_tools_metadata,
    get_tool_by_name,
    locked_tool_registry_state,
    normalize_authored_tool_overrides,
    resolved_tool_metadata_for_runtime,
    resolved_tool_validation_snapshot_for_runtime,
    restore_plugin_tool_registrations,
    restore_tool_registry_snapshot,
    sanitize_tool_init_overrides,
    scoped_plugin_registration_owner,
    serialize_tool_validation_snapshot,
    snapshot_plugin_tool_registrations,
    synchronize_plugin_tools,
    validate_authored_tool_entry_overrides,
)

__all__ = [
    "ConfigField",
    "SetupType",
    "TOOL_METADATA",
    "_TOOL_REGISTRY",
    "ToolAuthoredOverrideValidator",
    "ToolCategory",
    "ToolConfigOverrideError",
    "ToolInitOverrideError",
    "ToolMetadata",
    "ToolMetadataValidationError",
    "ToolStatus",
    "ToolValidationInfo",
    "apply_authored_overrides",
    "authored_tool_overrides_to_runtime",
    "default_worker_routed_tools",
    "deserialize_tool_validation_snapshot",
    "ensure_tool_registry_loaded",
    "export_tools_metadata",
    "get_tool_by_name",
    "normalize_authored_tool_overrides",
    "resolved_tool_metadata_for_runtime",
    "resolved_tool_validation_snapshot_for_runtime",
    "sanitize_tool_init_overrides",
    "serialize_tool_validation_snapshot",
    "validate_authored_tool_entry_overrides",
    "synchronize_plugin_tools",
    "capture_tool_registry_snapshot",
    "restore_tool_registry_snapshot",
    "locked_tool_registry_state",
    "clear_plugin_tool_registrations",
    "snapshot_plugin_tool_registrations",
    "restore_plugin_tool_registrations",
    "scoped_plugin_registration_owner",
]
