"""Public runtime facade for tool execution helpers."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mindroom.tool_system.dependencies import (
        auto_install_enabled,
        auto_install_tool_extra,
        check_deps_installed,
        ensure_optional_deps,
        ensure_tool_deps,
        install_command_for_current_python,
    )
    from mindroom.tool_system.events import (
        StructuredStreamChunk,
        ToolTraceEntry,
        build_tool_trace_content,
        complete_pending_tool_block,
        extract_tool_completed_info,
        format_tool_combined,
        format_tool_completed_event,
        format_tool_started_event,
    )
    from mindroom.tool_system.plugin_identity import validate_plugin_name
    from mindroom.tool_system.runtime_context import (
        LiveToolDispatchContext,
        ToolDispatchContext,
        ToolRuntimeContext,
        ToolRuntimeHookBindings,
        ToolRuntimeSupport,
        append_tool_runtime_attachment_id,
        attachment_id_available_in_tool_runtime_context,
        build_scheduling_runtime_from_tool_runtime_context,
        emit_custom_event,
        get_plugin_state_root,
        get_tool_runtime_context,
        list_tool_runtime_attachment_ids,
        resolve_current_session_id,
        resolve_tool_runtime_hook_bindings,
        runtime_context_from_dispatch_context,
        tool_runtime_context,
    )
    from mindroom.tool_system.sandbox_proxy import (
        maybe_wrap_toolkit_for_sandbox_proxy,
        sandbox_proxy_config,
        to_json_compatible,
    )
    from mindroom.tool_system.tool_hooks import build_tool_hook_bridge, prepend_tool_hook_bridge
    from mindroom.tool_system.worker_routing import (
        ResolvedWorkerTarget,
        ToolExecutionIdentity,
        WorkerScope,
        active_tool_execution_identity,
        agent_state_root_path,
        agent_workspace_relative_path,
        agent_workspace_root_path,
        build_tool_execution_identity,
        build_worker_target_from_runtime_env,
        get_tool_execution_identity,
        local_shared_credential_allowlist,
        private_instance_scope_root_path,
        require_worker_key_for_scope,
        requires_shared_only_integration_scope,
        resolve_agent_owned_path,
        resolve_agent_state_storage_path,
        resolve_unscoped_worker_key,
        resolve_worker_execution_scope,
        resolve_worker_key,
        resolve_worker_target,
        resolved_worker_key_scope,
        run_with_tool_execution_identity,
        service_uses_local_shared_credentials,
        shared_storage_root,
        stream_with_tool_execution_identity,
        supports_tool_name_for_worker_scope,
        tool_execution_identity,
        unsupported_shared_only_integration_message,
        unsupported_shared_only_integration_names,
        visible_state_roots_for_worker_key,
        worker_dir_name,
        worker_root_path,
        worker_scope_allows_shared_only_integrations,
    )

_EXPORT_MODULES = {
    "auto_install_enabled": "mindroom.tool_system.dependencies",
    "auto_install_tool_extra": "mindroom.tool_system.dependencies",
    "check_deps_installed": "mindroom.tool_system.dependencies",
    "ensure_optional_deps": "mindroom.tool_system.dependencies",
    "ensure_tool_deps": "mindroom.tool_system.dependencies",
    "install_command_for_current_python": "mindroom.tool_system.dependencies",
    "LiveToolDispatchContext": "mindroom.tool_system.runtime_context",
    "ToolDispatchContext": "mindroom.tool_system.runtime_context",
    "ToolRuntimeContext": "mindroom.tool_system.runtime_context",
    "ToolRuntimeHookBindings": "mindroom.tool_system.runtime_context",
    "ToolRuntimeSupport": "mindroom.tool_system.runtime_context",
    "append_tool_runtime_attachment_id": "mindroom.tool_system.runtime_context",
    "attachment_id_available_in_tool_runtime_context": "mindroom.tool_system.runtime_context",
    "build_scheduling_runtime_from_tool_runtime_context": "mindroom.tool_system.runtime_context",
    "emit_custom_event": "mindroom.tool_system.runtime_context",
    "get_plugin_state_root": "mindroom.tool_system.runtime_context",
    "get_tool_runtime_context": "mindroom.tool_system.runtime_context",
    "list_tool_runtime_attachment_ids": "mindroom.tool_system.runtime_context",
    "resolve_current_session_id": "mindroom.tool_system.runtime_context",
    "resolve_tool_runtime_hook_bindings": "mindroom.tool_system.runtime_context",
    "runtime_context_from_dispatch_context": "mindroom.tool_system.runtime_context",
    "tool_runtime_context": "mindroom.tool_system.runtime_context",
    "validate_plugin_name": "mindroom.tool_system.plugin_identity",
    "ResolvedWorkerTarget": "mindroom.tool_system.worker_routing",
    "ToolExecutionIdentity": "mindroom.tool_system.worker_routing",
    "WorkerScope": "mindroom.tool_system.worker_routing",
    "active_tool_execution_identity": "mindroom.tool_system.worker_routing",
    "agent_state_root_path": "mindroom.tool_system.worker_routing",
    "agent_workspace_relative_path": "mindroom.tool_system.worker_routing",
    "agent_workspace_root_path": "mindroom.tool_system.worker_routing",
    "build_tool_execution_identity": "mindroom.tool_system.worker_routing",
    "build_worker_target_from_runtime_env": "mindroom.tool_system.worker_routing",
    "get_tool_execution_identity": "mindroom.tool_system.worker_routing",
    "local_shared_credential_allowlist": "mindroom.tool_system.worker_routing",
    "private_instance_scope_root_path": "mindroom.tool_system.worker_routing",
    "require_worker_key_for_scope": "mindroom.tool_system.worker_routing",
    "resolve_agent_owned_path": "mindroom.tool_system.worker_routing",
    "resolve_agent_state_storage_path": "mindroom.tool_system.worker_routing",
    "resolve_unscoped_worker_key": "mindroom.tool_system.worker_routing",
    "resolve_worker_execution_scope": "mindroom.tool_system.worker_routing",
    "resolve_worker_key": "mindroom.tool_system.worker_routing",
    "resolve_worker_target": "mindroom.tool_system.worker_routing",
    "resolved_worker_key_scope": "mindroom.tool_system.worker_routing",
    "requires_shared_only_integration_scope": "mindroom.tool_system.worker_routing",
    "run_with_tool_execution_identity": "mindroom.tool_system.worker_routing",
    "service_uses_local_shared_credentials": "mindroom.tool_system.worker_routing",
    "shared_storage_root": "mindroom.tool_system.worker_routing",
    "stream_with_tool_execution_identity": "mindroom.tool_system.worker_routing",
    "supports_tool_name_for_worker_scope": "mindroom.tool_system.worker_routing",
    "tool_execution_identity": "mindroom.tool_system.worker_routing",
    "unsupported_shared_only_integration_message": "mindroom.tool_system.worker_routing",
    "unsupported_shared_only_integration_names": "mindroom.tool_system.worker_routing",
    "visible_state_roots_for_worker_key": "mindroom.tool_system.worker_routing",
    "worker_dir_name": "mindroom.tool_system.worker_routing",
    "worker_root_path": "mindroom.tool_system.worker_routing",
    "worker_scope_allows_shared_only_integrations": "mindroom.tool_system.worker_routing",
    "build_tool_hook_bridge": "mindroom.tool_system.tool_hooks",
    "prepend_tool_hook_bridge": "mindroom.tool_system.tool_hooks",
    "StructuredStreamChunk": "mindroom.tool_system.events",
    "ToolTraceEntry": "mindroom.tool_system.events",
    "build_tool_trace_content": "mindroom.tool_system.events",
    "complete_pending_tool_block": "mindroom.tool_system.events",
    "extract_tool_completed_info": "mindroom.tool_system.events",
    "format_tool_combined": "mindroom.tool_system.events",
    "format_tool_completed_event": "mindroom.tool_system.events",
    "format_tool_started_event": "mindroom.tool_system.events",
    "maybe_wrap_toolkit_for_sandbox_proxy": "mindroom.tool_system.sandbox_proxy",
    "sandbox_proxy_config": "mindroom.tool_system.sandbox_proxy",
    "to_json_compatible": "mindroom.tool_system.sandbox_proxy",
}

__all__ = [
    "LiveToolDispatchContext",
    "ResolvedWorkerTarget",
    "StructuredStreamChunk",
    "ToolDispatchContext",
    "ToolExecutionIdentity",
    "ToolRuntimeContext",
    "ToolRuntimeHookBindings",
    "ToolRuntimeSupport",
    "ToolTraceEntry",
    "WorkerScope",
    "active_tool_execution_identity",
    "agent_state_root_path",
    "agent_workspace_relative_path",
    "agent_workspace_root_path",
    "append_tool_runtime_attachment_id",
    "attachment_id_available_in_tool_runtime_context",
    "auto_install_enabled",
    "auto_install_tool_extra",
    "build_scheduling_runtime_from_tool_runtime_context",
    "build_tool_execution_identity",
    "build_tool_hook_bridge",
    "build_tool_trace_content",
    "build_worker_target_from_runtime_env",
    "check_deps_installed",
    "complete_pending_tool_block",
    "emit_custom_event",
    "ensure_optional_deps",
    "ensure_tool_deps",
    "extract_tool_completed_info",
    "format_tool_combined",
    "format_tool_completed_event",
    "format_tool_started_event",
    "get_plugin_state_root",
    "get_tool_execution_identity",
    "get_tool_runtime_context",
    "install_command_for_current_python",
    "list_tool_runtime_attachment_ids",
    "local_shared_credential_allowlist",
    "maybe_wrap_toolkit_for_sandbox_proxy",
    "prepend_tool_hook_bridge",
    "private_instance_scope_root_path",
    "require_worker_key_for_scope",
    "requires_shared_only_integration_scope",
    "resolve_agent_owned_path",
    "resolve_agent_state_storage_path",
    "resolve_current_session_id",
    "resolve_tool_runtime_hook_bindings",
    "resolve_unscoped_worker_key",
    "resolve_worker_execution_scope",
    "resolve_worker_key",
    "resolve_worker_target",
    "resolved_worker_key_scope",
    "run_with_tool_execution_identity",
    "runtime_context_from_dispatch_context",
    "sandbox_proxy_config",
    "service_uses_local_shared_credentials",
    "shared_storage_root",
    "stream_with_tool_execution_identity",
    "supports_tool_name_for_worker_scope",
    "to_json_compatible",
    "tool_execution_identity",
    "tool_runtime_context",
    "unsupported_shared_only_integration_message",
    "unsupported_shared_only_integration_names",
    "validate_plugin_name",
    "visible_state_roots_for_worker_key",
    "worker_dir_name",
    "worker_root_path",
    "worker_scope_allows_shared_only_integrations",
]


def __getattr__(name: str) -> object:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
